autoInstallPeers: false
publicHoistPattern:
  - '*storybook*'
# Enforce that packages must be at least 2 days old before they're installed
# This reduces the risk of supply chain attacks from newly published packages
minimumReleaseAge: 2880
packages:
  - 'packages/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!packages/typescript/test/**'
  - '!packages/kiosk/test/**'
  - '!packages/deepbook/test/**'
  - '!packages/codegen/tests/move/**'
  - '!packages/create-dapp/templates'
  - '!packages/typescript/scripts'
  - '!packages/typescript/transactions'
  - '!packages/typescript/cryptography'
  - '!packages/typescript/faucet'
  - '!packages/typescript/client'
  - '!packages/typescript/verify'
  - '!packages/typescript/multisig'
  - '!packages/typescript/utils'
  - '!packages/typescript/bcs'
  - '!packages/enoki/react'
  - '!packages/typescript/graphql'
  - '!packages/typescript/keypairs/ed25519'
  - '!packages/typescript/keypairs/secp256k1'
  - '!packages/typescript/keypairs/secp256r1'
  - '!packages/typescript/graphql/schemas/2024.1'
  - '!packages/typescript/graphql/schemas/2024.4'
  - '!packages/signers/aws'
  - '!packages/signers/gcp'
  - '!packages/signers/ledger'
  - '!packages/typescript/zklogin'
  - '!packages/typescript/keypairs/passkey'
  - '!packages/typescript/graphql/schemas/latest'
  - '!packages/signers/utils'
  - '!packages/signers/webcrypto'
  - '!packages/zksend/experimental/unified-adapter'
  - '!packages/typescript/experimental'
  - '!packages/dapp-kit-next/packages/dapp-kit-core/web'
  - '!packages/typescript/grpc'
  - '!packages/typescript/jsonRpc'
