// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

import * as fs from 'node:fs';
import * as path from 'node:path';

const packageRoot = path.resolve(import.meta.url.slice(5), '../..');
const protoDir = path.join(packageRoot, 'src/grpc/proto/sui/rpc/v2');
const outputFile = path.join(packageRoot, 'src/grpc/proto/types.ts');

// Get all .ts files in the proto directory, excluding .client.ts files
const files = fs
	.readdirSync(protoDir)
	.filter((file) => file.endsWith('.ts') && !file.endsWith('.client.ts'))
	.sort();

const header = `// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is auto-generated by scripts/generate-grpc-types.ts
 * Run \`pnpm codegen:grpc\` to regenerate.
 */

// Re-export all gRPC proto types for easy consumption
`;

const exports = files.map((file) => {
	const moduleName = file.replace('.ts', '.js');
	return `export * from './sui/rpc/v2/${moduleName}';`;
});

const content = header + exports.join('\n') + '\n';

fs.writeFileSync(outputFile, content);

console.log(`Generated ${outputFile} with ${files.length} exports`);
