// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// @generated by protobuf-ts 2.9.6 with parameter force_server_none,optimize_code_size,ts_nocheck
// @generated from protobuf file "sui/rpc/v2beta2/live_data_service.proto" (package "sui.rpc.v2beta2", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
import type { RpcTransport } from '@protobuf-ts/runtime-rpc';
import type { ServiceInfo } from '@protobuf-ts/runtime-rpc';
import { LiveDataService } from './live_data_service.js';
import type { SimulateTransactionResponse } from './live_data_service.js';
import type { SimulateTransactionRequest } from './live_data_service.js';
import type { ListBalancesResponse } from './live_data_service.js';
import type { ListBalancesRequest } from './live_data_service.js';
import type { GetBalanceResponse } from './live_data_service.js';
import type { GetBalanceRequest } from './live_data_service.js';
import type { GetCoinInfoResponse } from './live_data_service.js';
import type { GetCoinInfoRequest } from './live_data_service.js';
import type { ListOwnedObjectsResponse } from './live_data_service.js';
import type { ListOwnedObjectsRequest } from './live_data_service.js';
import { stackIntercept } from '@protobuf-ts/runtime-rpc';
import type { ListDynamicFieldsResponse } from './live_data_service.js';
import type { ListDynamicFieldsRequest } from './live_data_service.js';
import type { UnaryCall } from '@protobuf-ts/runtime-rpc';
import type { RpcOptions } from '@protobuf-ts/runtime-rpc';
/**
 * @generated from protobuf service sui.rpc.v2beta2.LiveDataService
 */
export interface ILiveDataServiceClient {
	/**
	 * @generated from protobuf rpc: ListDynamicFields(sui.rpc.v2beta2.ListDynamicFieldsRequest) returns (sui.rpc.v2beta2.ListDynamicFieldsResponse);
	 */
	listDynamicFields(
		input: ListDynamicFieldsRequest,
		options?: RpcOptions,
	): UnaryCall<ListDynamicFieldsRequest, ListDynamicFieldsResponse>;
	/**
	 * @generated from protobuf rpc: ListOwnedObjects(sui.rpc.v2beta2.ListOwnedObjectsRequest) returns (sui.rpc.v2beta2.ListOwnedObjectsResponse);
	 */
	listOwnedObjects(
		input: ListOwnedObjectsRequest,
		options?: RpcOptions,
	): UnaryCall<ListOwnedObjectsRequest, ListOwnedObjectsResponse>;
	/**
	 * @generated from protobuf rpc: GetCoinInfo(sui.rpc.v2beta2.GetCoinInfoRequest) returns (sui.rpc.v2beta2.GetCoinInfoResponse);
	 */
	getCoinInfo(
		input: GetCoinInfoRequest,
		options?: RpcOptions,
	): UnaryCall<GetCoinInfoRequest, GetCoinInfoResponse>;
	/**
	 * @generated from protobuf rpc: GetBalance(sui.rpc.v2beta2.GetBalanceRequest) returns (sui.rpc.v2beta2.GetBalanceResponse);
	 */
	getBalance(
		input: GetBalanceRequest,
		options?: RpcOptions,
	): UnaryCall<GetBalanceRequest, GetBalanceResponse>;
	/**
	 * @generated from protobuf rpc: ListBalances(sui.rpc.v2beta2.ListBalancesRequest) returns (sui.rpc.v2beta2.ListBalancesResponse);
	 */
	listBalances(
		input: ListBalancesRequest,
		options?: RpcOptions,
	): UnaryCall<ListBalancesRequest, ListBalancesResponse>;
	/**
	 * @generated from protobuf rpc: SimulateTransaction(sui.rpc.v2beta2.SimulateTransactionRequest) returns (sui.rpc.v2beta2.SimulateTransactionResponse);
	 */
	simulateTransaction(
		input: SimulateTransactionRequest,
		options?: RpcOptions,
	): UnaryCall<SimulateTransactionRequest, SimulateTransactionResponse>;
}
/**
 * @generated from protobuf service sui.rpc.v2beta2.LiveDataService
 */
export class LiveDataServiceClient implements ILiveDataServiceClient, ServiceInfo {
	typeName = LiveDataService.typeName;
	methods = LiveDataService.methods;
	options = LiveDataService.options;
	constructor(private readonly _transport: RpcTransport) {}
	/**
	 * @generated from protobuf rpc: ListDynamicFields(sui.rpc.v2beta2.ListDynamicFieldsRequest) returns (sui.rpc.v2beta2.ListDynamicFieldsResponse);
	 */
	listDynamicFields(
		input: ListDynamicFieldsRequest,
		options?: RpcOptions,
	): UnaryCall<ListDynamicFieldsRequest, ListDynamicFieldsResponse> {
		const method = this.methods[0],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<ListDynamicFieldsRequest, ListDynamicFieldsResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: ListOwnedObjects(sui.rpc.v2beta2.ListOwnedObjectsRequest) returns (sui.rpc.v2beta2.ListOwnedObjectsResponse);
	 */
	listOwnedObjects(
		input: ListOwnedObjectsRequest,
		options?: RpcOptions,
	): UnaryCall<ListOwnedObjectsRequest, ListOwnedObjectsResponse> {
		const method = this.methods[1],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<ListOwnedObjectsRequest, ListOwnedObjectsResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: GetCoinInfo(sui.rpc.v2beta2.GetCoinInfoRequest) returns (sui.rpc.v2beta2.GetCoinInfoResponse);
	 */
	getCoinInfo(
		input: GetCoinInfoRequest,
		options?: RpcOptions,
	): UnaryCall<GetCoinInfoRequest, GetCoinInfoResponse> {
		const method = this.methods[2],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<GetCoinInfoRequest, GetCoinInfoResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: GetBalance(sui.rpc.v2beta2.GetBalanceRequest) returns (sui.rpc.v2beta2.GetBalanceResponse);
	 */
	getBalance(
		input: GetBalanceRequest,
		options?: RpcOptions,
	): UnaryCall<GetBalanceRequest, GetBalanceResponse> {
		const method = this.methods[3],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<GetBalanceRequest, GetBalanceResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: ListBalances(sui.rpc.v2beta2.ListBalancesRequest) returns (sui.rpc.v2beta2.ListBalancesResponse);
	 */
	listBalances(
		input: ListBalancesRequest,
		options?: RpcOptions,
	): UnaryCall<ListBalancesRequest, ListBalancesResponse> {
		const method = this.methods[4],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<ListBalancesRequest, ListBalancesResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
	/**
	 * @generated from protobuf rpc: SimulateTransaction(sui.rpc.v2beta2.SimulateTransactionRequest) returns (sui.rpc.v2beta2.SimulateTransactionResponse);
	 */
	simulateTransaction(
		input: SimulateTransactionRequest,
		options?: RpcOptions,
	): UnaryCall<SimulateTransactionRequest, SimulateTransactionResponse> {
		const method = this.methods[5],
			opt = this._transport.mergeOptions(options);
		return stackIntercept<SimulateTransactionRequest, SimulateTransactionResponse>(
			'unary',
			this._transport,
			method,
			opt,
			input,
		);
	}
}
