---
name: Seal Integration tests
on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [seal-integration-tests]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # pin@v3.0.0
        with:
          version: 9.1.1
      - name: Install Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Seal dependencies
        run: pnpm turbo build --filter @mysten/seal

      - name: Run integration tests
        run: pnpm --filter @mysten/seal test:unit
